import Head from "next/head";
import styles from "../styles/Search.module.scss";
import Image from "next/image";
import Form from "./form";
import Settings from "./settings";
import React from "react";

function Header(props: { title?: string | string[] | '', searchField?: boolean | false }) {
    return (
        <>
            <Head>
                <title>ultimEngine {props.title}</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={styles.form_container}>
                <a href={'/'}>
                            <span className={styles.logo}>
                                <Image src="/logo.svg" alt="Out logo" width={144} height={32} className={styles.svg}/>
                            </span>
                </a>
                {props.searchField && <Form/>}
                <Settings/>
            </div>
        </>
    )
}

export default Header