import styles from "../styles/About.module.scss";
import Head from "next/head";
import Form from "../components/form";
import Image from "next/image"

function About() {
    return (
        <div className={styles.container}>
            <Head>
                <title>ultimEngine Help</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <div className={styles.content}>
                    <h1>Settings</h1>
                    <div className={styles.content_container}>
                        <h2></h2>
                        <input type={"checkbox"}/>
                        <label>Use dark theme</label>
                    </div>
                    <h1>About</h1>
                    <div className={styles.content_container}>
                        <h2>ultimEngine</h2>
                        <p>ultimEngine is a fully working search engine with its front-end written in TypeScript in the Next.js framework and back-end written mainly in Kotlin</p>
                        <h2>Our Team</h2>
                        <div className={styles.image_section}>
                            <div className={styles.image_group}>
                                <Image className={styles.image_img} alt={"David Stoček"} src={"/stocekd.png"} layout={"responsive"} width={1} height={1}/>
                                <p><b>David Stoček</b><br/>Front-end developer</p>
                            </div>
                            <div className={styles.image_group}>
                                <Image className={styles.image_img} alt={"Filip Hostinský"} src={"/hostinskyf.jpeg"} layout={"responsive"} width={1} height={1}/>
                                <p><b>Filip Hostinský</b><br/>Project lead, back-end developer, znalec astrálních plání</p>
                            </div>
                            <div className={styles.image_group}>
                                <Image className={styles.image_img} alt={"Vojtěch Binar"} src={"/binarv.jpg"} layout={"responsive"} width={1} height={1}/>
                                <p><b>Vojtěch Binar</b><br/>Back-end developer</p>
                            </div>
                            {/*<div className={styles.image_group}>*/}
                            {/*    <Image className={styles.image_img} alt={"David Stoček"} src={"/rom.png"} layout={"responsive"} width={1} height={1}/>*/}
                            {/*    <p><b>David Stoček</b><br/>Great romantic<br/></p>*/}
                            {/*</div>*/}
                            {/*<div className={styles.image_group}>*/}
                            {/*    <Image className={styles.image_img} alt={"David Stoček"} src={"/alc.png"} layout={"responsive"} width={1} height={1}/>*/}
                            {/*    <p><b>David Stoček</b><br/>Alcoholic<br/>Bringer of drinks</p>*/}
                            {/*</div>*/}
                            {/*<div className={styles.image_group}>*/}
                            {/*    <Image className={styles.image_img} alt={"David Stoček"} src={"/gay.png"} layout={"responsive"} width={1} height={1}/>*/}
                            {/*    <p><b>David Stoczek</b><br/>Gay marriage supporter<br/></p>*/}
                            {/*</div>*/}
                        </div>
                    </div>
                </div>
            </main>
        </div>
    )
}

export default About