import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Form from "../components/form";
import {theme_changer} from "../scripts/theme_changer";

function Home() {

    if (typeof window !== 'undefined'){
        let temp = localStorage.getItem('theme')
        // @ts-ignore
        theme_changer(temp)
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>ultimEngine</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <div className={styles.main_div}>
                    <span className={styles.logo}>
                        <Image className={styles.svg} src="/logo.svg" alt="Out logo" width={144} height={32}/>
                    </span>
                    <Form/>
                </div>
            </main>
        </div>
    )
}

export default Home
