import styles from '../styles/Search.module.scss'
import Head from "next/head";
import {useRouter} from "next/router";
import Result from "../components/result";
import Form from "../components/form";
import React, { useState } from 'react';
import Hint from "../components/hint";

function Search(data: any){
    // On start request data from Filip
    // On scroll to the bottom, request new data from Filip

    const router = useRouter()
    const query = router.query

    // const [results, chResults] = useState(data.data.fulltext.results)

    const results = data.data.fulltext.results

    //const [hints, chHints] = useState(data.data.hints.results)

    // const hints = data.data.fulltext.hints

    const suggests = [
        {query: "iservery"},
        {query: "grussmann"},
        {query: "why do i pee white"},
        {query: "mr hands"},
        {query: "skolaonline"},
        {query: "velky krtkus"},
        {query: "okkr"},
        {query: "how to seduce a woman"},
        {query: "nfs neni need for speed"},
        {query: "what is kvadrant"}
    ]

    return (
        <div className={styles.container}>
            <Head>
                <title>ultimEngine - {query.q}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.form_container}>
                <Form data={suggests}/>
            </div>
            <main className={styles.main}>
                <div className={styles.grid_container}>
                    <div className={styles.results} id={'results'}>
                        {results.map((element: any, i:number) => {return(<Result data={element} key={i}/>)})}
                    </div>
                    <div className={styles.hints}>
                        {/*{hints.map((element: any, i:number) => {return(<Hint data={element} key={i}/>)})}*/}
                    </div>
                </div>
            </main>
        </div>
    )
}

export default Search

export async function getServerSideProps(context: any) {

    // const res = await fetch(`http://192.168.1.242:8080${context.resolvedUrl}`)
    // const data = await res.json()

     const data = {
        fulltext: {
            results: [
                {
                    url: "https://github.com",
                    title: "GitHub: Where the world builds software · GitHub",
                    description: "GitHub is where people build software. More than 73 million people use GitHub to discover, fork, and contribute to over 200 million projects."
                },
                {
                    url: "https://github.com",
                    title: "GitHub: Where the world builds software · GitHub",
                    description: "GitHub is where people build software. More than 73 million people use GitHub to discover, fork, and contribute to over 200 million projects."
                },
                {
                    url: "https://github.com",
                    title: "GitHub: Where the world builds software · GitHub",
                    description: "GitHub is where people build software. More than 73 million people use GitHub to discover, fork, and contribute to over 200 million projects."
                },
                {
                    url: "https://github.com",
                    title: "GitHub: Where the world builds software · GitHub",
                    description: "GitHub is where people build software. More than 73 million people use GitHub to discover, fork, and contribute to over 200 million projects."
                },
                {
                    url: "https://github.com",
                    title: "GitHub: Where the world builds software · GitHub",
                    description: "GitHub is where people build software. More than 73 million people use GitHub to discover, fork, and contribute to over 200 million projects."
                },
                {
                    url: "https://github.com",
                    title: "GitHub: Where the world builds software · GitHub",
                    description: "GitHub is where people build software. More than 73 million people use GitHub to discover, fork, and contribute to over 200 million projects."
                },
                {
                    url: "https://github.com",
                    title: "GitHub: Where the world builds software · GitHub",
                    description: "GitHub is where people build software. More than 73 million people use GitHub to discover, fork, and contribute to over 200 million projects."
                },
                {
                    url: "https://github.com",
                    title: "GitHub: Where the world builds software · GitHub",
                    description: "GitHub is where people build software. More than 73 million people use GitHub to discover, fork, and contribute to over 200 million projects."
                },
                {
                    url: "https://github.com",
                    title: "GitHub: Where the world builds software · GitHub",
                    description: "GitHub is where people build software. More than 73 million people use GitHub to discover, fork, and contribute to over 200 million projects."
                },
                {
                    url: "https://github.com",
                    title: "GitHub: Where the world builds software · GitHub",
                    description: "GitHub is where people build software. More than 73 million people use GitHub to discover, fork, and contribute to over 200 million projects."
                }
            ]
        },
        hints: {
            results: [
                {
                    title: "343 Industries",
                    category: "Video game industry company",
                    web: "https://www.343industries.com/",
                    description: "343 Industries is an American video game developer located in Redmond, Washington, part of Xbox Game Studios. Headed by Bonnie Ross, the studio is responsible for the Halo series of military science fiction games, originally created and produced by Bungie, and is the developer of the Slipspace Engine.",
                    wiki: "https://en.wikipedia.org/wiki/343_Industries"
                },
                {
                    title: "343 Industries",
                    qdesc: "Video game industry company",
                    website: "https://www.343industries.com/",
                    website_cut: "343industries.com",
                    description: "343 Industries is an American video game developer located in Redmond, Washington, part of Xbox Game Studios. Headed by Bonnie Ross, the studio is responsible for the Halo series of military science fiction games, originally created and produced by Bungie, and is the developer of the Slipspace Engine.",
                    wiki: "https://en.wikipedia.org/wiki/343_Industries"
                }
            ]
        }
    }


    let tempResults = data.fulltext.results
    for (let i = 0; i < tempResults.length; i++){
        if (tempResults[i].title.length > 50){
            let temp = tempResults[i].title.substr(0, 50).split(' ')
            temp.splice(-1)
            tempResults[i].title = `${temp.join(' ')} ...`
        }
    }

    data.fulltext.results = tempResults

    return { props: { data } }
}